import time
from pathlib import Path

rule touch_dep1:
    output:
        "tmp/dep1.txt"
    run:
        time.sleep(5)
        Path(output[0]).touch()

rule touch_dep2:
    output:
        "tmp/dep2.txt"
    run:
        time.sleep(10)
        Path(output[0]).touch()

rule touch_dep3:
    output:
        "tmp/dep3.txt"
    run:
        time.sleep(5)
        Path(output[0]).touch()

rule aggregate_deps_ok:
    input:
        "tmp/dep1.txt",
        "tmp/dep2.txt",
        "tmp/dep3.txt"
    output:
        "out/result_ok.txt"
    run:
        time.sleep(3)
        Path(output[0]).touch()

rule aggregate_deps_and_fail:
    input:
        "tmp/dep1.txt",
        "tmp/dep2.txt",
        "tmp/dep3.txt"
    output:
        "out/result_fail.txt"
    log:
        "logs/aggregate_deps_and_fail.log"
    run:
        time.sleep(3)
        assert(False), "This rule will fail"
        Path(output[0]).touch()

rule aggregate_deps_and_missing_output:
    input:
        "tmp/dep1.txt",
        "tmp/dep2.txt",
        "tmp/dep3.txt"
    output:
        "out/result_missing.txt"
    run:
        time.sleep(3)

rule all_w_missing:
    input:
        "out/result_fail.txt"

rule all_w_fail:
    input:
        "out/result_fail.txt"

rule all:
    input:
        "out/result_ok.txt"
